import Link from "next/link";
import "./globals.css";

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pokemon = await fetch(
    "https://pokeapi.co/api/v2/pokemon/?limit=151"
  ).then((res) => res.json());

  return (
    <html lang="en" className="bg-slate-900 text-slate-200 font-mono">
      <head>
        <title>Next 13 Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="grid grid-cols-4">
        <aside className="p-4 text-sm h-screen overflow-scroll">
          <ul className="space-y-2">
            {pokemon.results.map((mon) => (
              <li key={mon.url}>
                <Link href={`/${mon.name}`}>{mon.name}</Link>
              </li>
            ))}
          </ul>
        </aside>
        <main className="col-span-3 p-4">{children}</main>
      </body>
    </html>
  );
}
