import Link from "next/link";
import "./globals.css";

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pokemon = await fetch("https://pokeapi.co/api/v2/pokemon/").then(
    (res) => res.json()
  );

  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <aside>
          <ul>
            {pokemon.results.map((mon) => (
              <li key={mon.url}>
                <Link href={`/${mon.name}`}>{mon.name}</Link>
              </li>
            ))}
          </ul>
        </aside>
        <main>{children}</main>
      </body>
    </html>
  );
}
